### ISSUE TITLE
[BUG] SSH Projects fail to load after latest Update

### ISSUE THREAD

**Issue by SirNovi** [beyondcode/invoker-community#152]
After the update to 2.3.1 (on macOS 10.15.7) my SSH Project does not load anymore. After Connection it just shows a blank page. Dev Tools don't even load ("DevTools was disconnected from the page.") 

I deleted the project and set it up again, same story. Goes into a blank page right after the connection and I have to kill the app. 

---
 
Additionally to this being fixed I would like to be able to **disable auto-updates**. I am using Invoker as my backend for a project with live streams. So I have to change settings in a timely manner. When I got the message "Update installed" I immediately thought "oh no, not now" and indeed, it's F'd up. 
Luckily all I am using Invoker for in this project is changing some values in a database, so I was able to just do that via phpMyAdmin, otherwise I would have been thoroughly screwed. This doesn't give me much confidence to rely solely on Invoker.

**Comment by pxlrbt** [comment]
I am running Invoker 2.3.1 on Windows and it's working fine.

**Comment by mpociot** [comment]
Hi @SirNovi,

sorry that you have experienced this issue in Invoker. All app updates go through a list of manual and automated checks to ensure that everything works.
Could you maybe get in touch with me via Telegram so that I can help you fix and debug this issue?

My Telegram username is `@mpociot` - thank you!

Regarding the auto-updates: Yeah, we'll add an option so that you can choose to skip an update.

**Comment by mpociot** [comment]
Okay - we managed to fix the SSH issue internally (thanks again @SirNovi for taking the time).
This will find its way into the next bugfix release. I think only a certain combination of servers/keys is affected by this - as all my existing keys and server combinations still work fine though.
