### ISSUE TITLE
WSL 2 Support Request

### ISSUE THREAD

**Issue by flexchar** [beyondcode/invoker-community#224]

**Comment by flexchar** [comment]
@sschlein I can't find release log. Does it means you've implemented or you are not interested in this future?

**Comment by xewl** [comment]
This has always worked, but you must run it from within WSL, with an X-server (eg X410) and the AppImage provided.

**Comment by flexchar** [comment]
Sounds like a workaround requiring unnecessary resource wasting (I think probably the biggest problem) rather than 1st party support. :)

**Comment by xewl** [comment]
PHP must run from the WSL Container in any case, and well.. it's a side effect of how this works. Going in from the Windows side is indeed a resource waste, and as a result: -very- slow. It's not really a workaround, it's actually the way to do this, like you would add your projects within the /home of the container itself, instead of via /mnt.

**Comment by flexchar** [comment]
Exactly. I love WSL 2 and do all development on Windows thanks to it. Very performant too! I have everything installed on Ubuntu distro + Docker for running the services. And VS Code remote works well. 

With this issue I have pictured that Invoker could also work like VS Code remote or as such. That wouldn't really be a resource waste in my opinion. What do you think?

**Comment by xewl** [comment]
I can write a book full of reasoning about this (kind of did). But the decision is on Beyondcodes' team. 

Running the X-server doesn't bring overhead,. it's quite performant, and has direct access to the virtual disk as opposed to running it from Windows.
It's not even more difficult than running docker containers.
(The initial setup is weird, but it works from that moment on.)

VSCode Remote is a thing on its own and "adapters" itself into WSL, running stuff from inside WSL (tunneling, commands, plugins, terminal) - great performance, for sure.


To me, AppImage is fine, and even.. wins. (because it already works fine as is :P)

**Comment by flexchar** [comment]
Sounds amazing! I'm not familiar with the set-up so I made assumption that it would be as running virtual machine inside wsl. Clearly I was wrong and happy to learn something new. Thank you.

**Comment by billyjustal** [comment]
anyone have a solution to getting their projects running with wsl2? via ssh? any one have any solution?

**Comment by xewl** [comment]
> anyone have a solution to getting their projects running with wsl2? via ssh? any one have any solution?

By now, WSL also introduced [WSLg](https://github.com/microsoft/wslg) (Which is a first-party implementation of an X-server).
It should be as simple as using the .AppImage, making it executable (+x) and executing it from within WSL itself.
