### ISSUE TITLE
[Feature Request]: Please, support for Laravel Sail and Docker is really needed!

### ISSUE THREAD

**Issue by jonagoldman** [beyondcode/invoker-community#327]
### Feature Description

I use Laravel Sail and Docker Compose for all of my work. Most of my coworkers and friends do the same or similar.
First-party support for Sail and Docker is essential and needed, and has being requested many times before.

The few workarounds available are frustrating, repetitive, time consuming and unstable. Hell.

On the other hand, support in Tinkerwell was added more than 6 months ago, improved over time and now works very well with just a few clicks. Such simplicity and stability can't be expected from Invoker on day one, but the issue need to be addressed.  Thanks :pray: 

### Is this feature valuable for other users as well and why?

This will be very much appreciated by all the Invoker customers using containers for development (most of us) , and save us all a lot of time and frustration.

**Comment by flexchar** [comment]
Frankly, I feel like this is the reason why bigger companies suck. They buy products and then collect revenue from sales but cut any development. 

I am indeed frustrated that this is not supported because I purchased a year ago, on email they answered they have been working on it _very hard_. Yet nothing comes. 

As a dev working on the team, I don't have the _luxury_ of running laravel without docker. All deployments and work is containerized. Yet no good support. Tinkerwell is also often not loading Docker. 

It's a really bad light upon the company. But well, a great example how to make money :))

**Comment by mechelon** [comment]
Invoker 2.13.0 now supports Docker for projects.
