### ISSUE TITLE
Support for docker network environments

### ISSUE THREAD

**Issue by kilrizzy** [beyondcode/invoker-community#43]
For example, my current local project is using a networked Docker, so while my app's env will contain:

```
DB_HOST=mysql
DB_PORT=3306
```

Accessing my database outside docker I would typically use something like

```
DB_HOST=local ip
DB_POST=3379
```

Some way to have invoker connect to my database via a docker container would be ideal

**Comment by chefhasteeth** [comment]
One solution to this would be allowing the user to override the .env values when opening a project (eg. a separate database settings dialog). Although, this might be pretty limited in usefulness because it still requires a local php install. At that point it's hard to guarantee your local php and the docker instance are the same.

**Comment by chefhasteeth** [comment]
I just got this working on my end. In /etc/hosts, I added an alias for `127.0.0.1 mysql`. Suddenly Invoker has access to my docker db instance.

**Comment by mpociot** [comment]
We'll add this to our documentation 👍
