### ISSUE TITLE
Error: spawn /usr/local/bin/php ENOENT

### ISSUE THREAD

**Issue by dhruva81** [beyondcode/invoker-community#46]
------
**OS**: win32
**Invoker Version**: 2.0.1
**PHP Binary**: /usr/local/bin/php
**Route**: /home

**Error**:
```
Error: spawn /usr/local/bin/php ENOENT
```

**Comment by sschlein** [comment]
We have a bug in the automated detection of the correct PHP version. Can you check if it works if you set it manually in the settings?

**Comment by dhruva81** [comment]
I manually set the PHP Binary path 
```
C:\laragon\bin\php\php-7.4.8-Win32-vc15-x64\php.exe
```
and it worked perfectly, thank you so much!

**Comment by ukjadoon** [comment]
@mpociot @sschlein I think I am still having the issue with this error (I sent an email to support too earlier today). I am on WSL2 and running X applications via VcXsrv

------
 
**OS**: linux
 
**Invoker Version**: 2.0.1
 
**PHP Binary**: /usr/local/bin/php
 
**Route**: /home
 
 
 
**Error**:
 
```
Error: spawn /usr/local/bin/php ENOENT

```

In my case, since the application is running on Linux, `/usr/bin/php` is the correct path of PHP.

This is my terminal output,

```
./Invoker-2.0.1.AppImage --no-sandbox
loading plugins :: /root/.config/Invoker/plugins
run autoupdater
(node:26880) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of E
lectron.  See https://github.com/electron/electron/issues/23506 for more information
Unable to install `vue-devtools`:
Error: Exited with code 9
    at ChildProcess.<anonymous> (/tmp/.mount_InvokegAXfbr/resources/app.asar/dist/electron/main.js:1:83318)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
PLUGINS:  [] []
PLUGINS:  [] []
```

Path of the PHP binary

```
╰─ which php
/usr/bin/php
```

PHP version

```
 php --version
PHP 7.4.9 (cli) (built: Aug  7 2020 14:29:36) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies
```

Tinkerwell seems to work fine on the same setup though (and so does Spatie's Ray App)

**Comment by ukjadoon** [comment]
just to add to my previous comment (and I also forgot to mention this in the email). The app opens just fine

![image](https://user-images.githubusercontent.com/549181/106663040-d7d7f700-65ab-11eb-9380-d52889cefef5.png)

The error happens when I actually open a project folder

![image](https://user-images.githubusercontent.com/549181/106663099-ede5b780-65ab-11eb-9d42-6325f6d42958.png)

**Comment by ukjadoon** [comment]
Alright, had to squint my eyes to see the issue,

```
which php
/usr/bin/php
```

And in my settings, the default was 

```
/usr/bin/local/php
```

Fixed the path, removed the `local` and now it is working. Sorry! 😞

**Comment by Naoray** [comment]
Faced this error is well. Just went to settings and even though the php path was the right one, the `Detected Version` wasn't detected and instead listed as `-`. I selected the exact same path as the app originally selected `/usr/bin/php` and it suddenly was able to detect the php version and the error was gone!
