### ISSUE TITLE
Artisan commands that require a response/confirmation never complete.

### ISSUE THREAD

**Issue by corsair** [beyondcode/invoker-community#62]
It appears that there may not be support for Artisan Commands that require a response or otherwise confirmations (Y/N) to progress through until completion.

Upon attempting to run the command it will indefinitely remain in the "Running" state, without responding with any status update or errors.

![image](https://user-images.githubusercontent.com/1847891/106689301-9d0e9880-6584-11eb-8448-3b7fce333265.png)

**Comment by mpociot** [comment]
Right...I wonder what's the best way to fix this. 
Showing an interactive "terminal" where you can actually confirm the commands would probably be the best idea, but also the most complicated one.

I think it'll be sufficient to show the live command output and be able to cancel execution for these cases.
And if your command requires confirmation, you would need to add a `--force` flag or similar so that Invoker can make use of that.

**Comment by corsair** [comment]
@mpociot Hm, here's a possible angle but not sure how it would work based on how you're currently handling everything.

What if Invoker detects that command requires feedback and:
1. Displays the latest/live command output (which should display what is being asked).
2. Provide a "dumb" input field to be able to send a follow-up value.
3. Rinse and repeat until the artisan command completes.

This should avoid the need for a true interactive terminal and more so is just a back and forth "telephone" until the command succeeds or fails.

Given that confirmations/additional context is a likely common use case for Artisan commands, this might be more worthwhile. Would love to know your thoughts.
