### ISSUE TITLE
Ability to add custom code to be pre-processed

### ISSUE THREAD

**Issue by hansensalim** [beyondcode/invoker-community#68]
This is a feature request for an option to add custom PHP code that will be executed before the Invoker queries. My main use case right now is similar to what is mentioned in #38 about multi tenancy. 

So for example, in my multi-tenancy application each user has their own dedicated database. In order to read the data that belonged to a tenant, I will need to run a simple code such as `app(TenantManager::class)->setTenant(User::first())` so that the DB connection are set to the specific database owned by that user. Just also want to quickly mention that feature request from #51 will not fix this issue as all tenants may use a single connection.

Outside of multi-tenancy context, this feature may also be desirable for other things such as overriding config values.

**Comment by mpociot** [comment]
Yeah, I think that's a good idea and also the most flexible solution for this. I'll see how we can add this. Invoker currently doesn't have per-project settings, where I would see this option. But we need it anyway in order to toggle the vendor scanning on/off based on the project and not just globally.

**Comment by mpociot** [comment]
I just published version 2.1.0, which adds support for custom "preload code" that you can specify per project.
This code gets evaluated before Invoker does it's thing, so you can use it to override configuration values, etc.
